version: "3.8"

services:
  eureka:
    build: ./eureka
    ports:
      - 8761:8761

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password

  currency:
    build: ./currency
    depends_on:
      - eureka
      - postgres
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS=
          -DEUREKA_SERVER=http://eureka:8761/eureka
          -DPOSTGRES_SERVER=jdbc:postgresql://postgres:5432/postgres

  weather:
    build: ./weather
    depends_on:
      - eureka
      - postgres
    ports:
      - 8081:8081
    environment:
      - JAVA_OPTS=
          -DEUREKA_SERVER=http://eureka:8761/eureka
          -DPOSTGRES_SERVER=jdbc:postgresql://postgres:5432/postgres

  predict:
    build: ./predict
    depends_on:
      - currency
      - weather
    ports:
      - 8082:8082
    environment:
      - JAVA_OPTS=
          -DEUREKA_SERVER=http://eureka:8761/eureka

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - currency
      - weather
      - predict

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
