apiVersion: v1
kind: Service
metadata:
  name: {{ include "eureka.fullname" . }}
  labels:
  {{- include "eureka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}
  selector:
  {{- include "eureka.selectorLabels" . | nindent 4 }}