apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  postgres_user: {{ .Values.config.postgres_user }}
  postgres_password: {{ .Values.config.postgres_password }}
