apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "postgres.fullname" . }}
      labels:
        {{- include "postgres.labels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ include "postgres.fullname" . }}-data
          persistentVolumeClaim:
            claimName: {{ include "postgres.fullname" . }}-pv-claim
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "postgres.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
{{- range $key, $value := .Values.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
{{- end }}
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: {{ include "postgres.fullname" . }}
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ include "postgres.fullname" . }}
              key: postgres_password
        ports:
          - name: {{ include "postgres.name" . }}
            containerPort: {{ .Values.config.port }}
        volumeMounts:
          - name: {{ include "postgres.fullname" . }}-data
            mountPath: {{ .Values.config.storage_directory }}
