apiVersion: v1
kind: Service
metadata:
  name: {{ include "predict.fullname" . }}
  labels:
  {{- include "predict.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.port }}
      targetPort: {{ .Values.config.port }}
  selector:
  {{- include "predict.selectorLabels" . | nindent 4 }}